language: ruby
env:
- MELBOURNE_SPEC_VERSION=1 RUBYLIB=lib:.
script: bundle exec rake
rvm:
- rbx
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
    on_success: change
    on_failure: always
    on_start: always
